formatter: "markdown table"

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: true
  path: modules

sections:
  hide: []
  show: []

content: |-
  # exp-net-fundamentals-2025-q2

    ## Infrastructure Diagram
    [Infrastructure Diagram](infrastructure-diagram.drawio)

    ## Usage

    ```hcl
    {{ include "main.tf" }}
    {{ include "variables.tf" }}
    ```

    {{ .Requirements }}

    {{ .Providers }}

    {{ .Modules }}

    {{ .Resources }}

    {{ .Inputs }}

    {{ .Outputs }}

    {{ .Footer }}

files:
  - main.tf
  - variables.tf
  - requirements.tf
  - providers.tf
  - outputs.tf
  - modules.tf
  - locals.tf
  - variables.tf
  - README.md
  - infrastructure-diagram.drawio

output:
  file: ""
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->


output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true