formatter: "markdown table"

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: true
  path: modules

sections:
  hide: []
  show: []

content: |-
  # Terraform Infrastructure

  {{ .Header }}

  ## Architecture Diagram
  
  ![Infrastructure Diagram](infrastructure-diagram.svg)
  
  [Interactive Diagram](rover-diagram.html) | [Draw.io Source](infrastructure-diagram.drawio)

  ## Usage

  ```hcl
  {{ include "main.tf" }}
  {{ include "provider.tf" }}
  {{ include "variables.tf" }}
  
  {{ include "./modules/aws-basic-network/locals.tf" }}
  {{ include "./modules/aws-basic-network/main.tf" }}
  {{ include "./modules/aws-basic-network/variables.tf" }}
  {{ include "./modules/aws-basic-network/output.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Footer }}

output:
  file: ""
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true